[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["VictorElHajj <hajjvictor@live.se>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
rayon = "1.5"
itertools = "0.9"
